name: ğŸ”„ï¸ CI

on:
  # https://blog.esciencecenter.nl/reduce-reuse-recycle-save-the-planet-one-github-action-at-a-time-4ab602255c3f
  push:
    paths:
      - .github/workflows/**
      - src/**
      - tests/**
      - package.json
      - .npmignore
      - bun.lock
      - bunfig.toml
      - tsup.config.ts
      - tsconfig*.json
      - '!**/*.md'

  pull_request:
    paths:
      - .github/workflows/**
      - src/**
      - tests/**
      - package.json
      - .npmignore
      - bun.lock
      - bunfig.toml
      - tsup.config.ts
      - tsconfig*.json
      - '!**/*.md'

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  pkg-pr-new:
    name: âš¡ pkg.pr.new
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            package.json
            .npmignore
            bun.lock
            bunfig.toml
            tsup.config.ts
            README.md
            LICENSE
            tsconfig*.json

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: âš’ï¸ Build package
        run: bun run build

      - name: âš¡ Publish prerelease
        run: bunx pkg-pr-new publish
