name: ğŸš€ Release + Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. 1.2.3)
        required: false
        default: conventional
        type: string

      run-tests:
        description: Run tests before release
        required: false
        default: false
        type: boolean

jobs:
  test:
    if: github.event.inputs.run-tests == 'true'
    permissions: {}
    uses: ./.github/workflows/tests.yml
    with:
      run-on-windows: true

  release:
    name: ğŸš€ Release
    needs: test
    if: ${{ !cancelled() && (needs.test.result == 'success' || needs.test.result == 'skipped') }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: ğŸ” Authentication for pushing to the main branch
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Required for fetching tags and generating release notes
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ”§ Configure Git
        run: |
          git config --global user.name  'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global push.followTags true

      - name: ğŸ“ˆ Bump version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: bunx bumpp@^10.2.0 $VERSION --commit --tag --push

      - name: ğŸ› ï¸ Build package
        run: bun run build

      - name: ğŸ“œ Generate changelog and create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          git checkout "$LATEST_TAG"

          bunx changelogithub@^13.16.0

      - name: ğŸ“¦ Publish to NPM Registry
        run: |
          bunx npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          bunx npm publish --provenance --access public
