on: [workflow_call]

permissions: {}

env:
  WINDOWS_USERPROFILE: D:\\

jobs:
  test:
    name: ðŸ§ª Tests
    strategy:
      fail-fast: false
      matrix:
        # Use older `windows-2019` for greater speed
        # See https://github.com/actions/runner-images/issues/5166
        os: [ubuntu-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      # https://ichard26.github.io/blog/2025/03/faster-pip-ci-on-windows-d-drive/#moving-temp-to-the-d-drive
      - name: ðŸ—‚ï¸ Set temp dir on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $TEMP_DIR = "$env:WINDOWS_USERPROFILE\Temp"
          # Create temp dir
          New-Item -ItemType Directory -Force -Path $TEMP_DIR | Out-Null

          "TEMP=$TEMP_DIR"  >> $env:GITHUB_ENV
          "TMP=$TEMP_DIR"   >> $env:GITHUB_ENV

      - name: ðŸ”“ Disable Windows Defender
        if: runner.os == 'Windows'
        shell: powershell
        run: Set-MpPreference -DisableRealtimeMonitoring $true

      - name: ðŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            tests
            package.json
            bun.lock
            bunfig.toml
            tsup.config.ts
            tsconfig*.json
            !**/*.md

      - name: ðŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest

      - name: ðŸ“¥ Cache Bun dependencies
        # Run only on Windows because on Linux there are no problems with slow package installation
        if: runner.os == 'Windows'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        env:
          USERPROFILE: ${{ env.WINDOWS_USERPROFILE }}
        with:
          path: '${{ env.USERPROFILE }}\.bun'
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: ðŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ðŸ§ª Run tests
        run: bun run test
