on: [workflow_call]

permissions: {}

env:
  WINDOWS_USERPROFILE: 'D:'
  BUN_CACHE_PATH: D:\.bun\install\cache

jobs:
  test:
    name: ğŸ§ª Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://ichard26.github.io/blog/2025/03/faster-pip-ci-on-windows-d-drive/#moving-temp-to-the-d-drive
      - name: ğŸ—‚ï¸ Configure Temp Directory (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $TEMP_DIR = "$env:WINDOWS_USERPROFILE\Temp"
          # Create temp dir
          New-Item -ItemType Directory -Force -Path $TEMP_DIR | Out-Null

          "TEMP=$TEMP_DIR"  >> $env:GITHUB_ENV
          "TMP=$TEMP_DIR"   >> $env:GITHUB_ENV

      - name: ğŸ”“ Disable Windows Defender (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: Set-MpPreference -DisableRealtimeMonitoring $true

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            tests
            package.json
            bun.lock
            bunfig.toml
            tsup.config.ts
            tsconfig*.json
            !**/*.md

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        env:
          USERPROFILE: ${{ env.WINDOWS_USERPROFILE }}
        with:
          bun-version: latest

        # Run only on Windows because on Linux there are no problems with slow package installation
      - name: ğŸ“¥ Cache Bun dependencies (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ${{ env.BUN_CACHE_PATH }}
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ matrix.os }}-bun-

        # The main bottleneck is here, `bun install` takes too long on Windows
        # @oven-sh Please fix this ğŸ™
      - name: ğŸ“¦ Install dependencies
        run: bun install --production --frozen-lockfile --prefer-offline --ignore-scripts

      - name: ğŸ§ª Run tests
        run: bun run test
